---
#do some stuff here to pull the kube config, install helm, pull the traefik chart and deploy traefik

- name: Create traefik config directory on first master
  file:
    path: /tmp/traefik-int
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy traefik chart values to first master
  template:
    src: "traefik-chart-values.yaml.j2"
    dest: /tmp/traefik-int/traefik-chart-values.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Copy traefik config to first master
  template:
    src: "traefik-config.yaml.j2"
    dest: /tmp/traefik-int/traefik-config.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Copy traefik dashboard manifest to first master
  template:
    src: "dashboard.yaml.j2"
    dest: /tmp/traefik-int/dashboard.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: add traefik helm repo
  command:
    cmd: "helm repo add traefik https://helm.traefik.io/traefik"
  changed_when: true

- name: update helm repo
  command:
    cmd: "helm repo update"
  changed_when: true

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: deploy traefik using helm
  command:
    cmd: "helm install traefik traefik/traefik \
      --namespace=kube-system \
      --values=/tmp/traefik-int/traefik-chart-values.yaml
      --wait"
  changed_when: true

- name: apply traefik default headers
  command:
    cmd: kubectl apply -f /tmp/traefik-int/traefik-config.yaml
  changed_when: true

- name: apply traefik dashboard
  command:
    cmd: kubectl apply -f /tmp/traefik-int/dashboard.yaml
  changed_when: true

- name: Clean up traefik tmp dir
  file:
    path: /tmp/traefik/
    state: absent
