---
- name: Create cert-manager config directory on first master
  file:
    path: /tmp/cert-manager
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: use_internal_ca | bool

- name: Copy values to first master
  template:
    src: "values.yaml.j2"
    dest: /tmp/cert-manager/values.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  when: use_internal_ca | bool

- name: Copy internal-ca to first master
  template:
    src: "internal-ca.yaml.j2"
    dest: /tmp/cert-manager/internal-ca.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  when: use_internal_ca | bool

- name: Copy ca-issuer to first master
  template:
    src: "ca-issuer.yaml.j2"
    dest: /tmp/cert-manager/ca-issuer.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  when: use_internal_ca | bool

- name: add cert-manager helm repo
  command:
    cmd: "helm repo add jetstack https://charts.jetstack.io"
  changed_when: true

- name: update helm repo
  command:
    cmd: "helm repo update"
  changed_when: true

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: apply cert-manager CRDs
  command:
    cmd: k3s kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_ver }}/cert-manager.crds.yaml
  retries: 2
  delay: 3
  changed_when: true

- name: create cert-manager namespace
  command:
    cmd: k3s kubectl create namespace cert-manager
  retries: 2
  delay: 3
  changed_when: true

- name: apply cert-manager internal-ca configmap
  command:
    cmd: k3s kubectl apply -f /tmp/cert-manager/internal-ca.yaml
  retries: 2
  delay: 3
  changed_when: true
  when: use_internal_ca | bool

- name: deploy cert-manager using helm with internal CA
  command:
    cmd: "helm install \
      cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --version {{ cert_manager_ver }} \
      --values=/tmp/cert-manager/values.yaml
      --wait"
  changed_when: true
  when: use_internal_ca | bool

- name: deploy cert-manager using helm without internal CA
  command:
    cmd: "helm install \
      cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --version {{ cert_manager_ver }} \
      --wait"
  changed_when: true
  when: not use_internal_ca | bool

- name: create internal CA issuer
  command:
    cmd: k3s kubectl apply -f /tmp/cert-manager/ca-issuer.yaml
  retries: 2
  delay: 3
  changed_when: true
  when: use_internal_ca | bool
